server:
  port: 8081

spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://localhost:3306/tms_auth_db
    username: tms_auth_user
    password: auth_pass_123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: a1b1c1d1e1f1gh57e9dbxhsa79snbdebfhe903bjidbc0884bd
  expiry-ms: 3600000

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan:
    - com.cap.identity.controller
