server:
  port: 8085

spring:
  application:
    name: admin-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/tms_admin_db}
    username: ${SPRING_DATASOURCE_USERNAME:tms_admin_db}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_pass_123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        auto-startup: true
        default-requeue-rejected: false

jwt:
  secret: ${JWT_SECRET:a1b1c1d1e1f1gh57e9dbxhsa79snbdebfhe903bjidbc0884bd}
  expiry-ms: ${JWT_EXPIRY_MS:3600000}

admin:
  timesheet-service-url: ${ADMIN_TIMESHEET_SERVICE_URL:http://localhost:8084}
  leave-service-url: ${ADMIN_LEAVE_SERVICE_URL:http://localhost:8083}

rabbitmq:
  exchanges:
    timesheet-events: timesheet.events
    leave-events: leave.events
    admin-commands: admin.commands
    master-data-sync: master.data.sync
    notification-events: notification.events

eureka:
  client:
     service-url:
        defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.cap.admin.controller